export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";

export const SET_CATEGORIES = "SET_CATEGORIES";
export const CLEAR_CATEGORIES = "SET_CATEGORIES";

export const SET_MENU_STATE = "SET_MENU_STATE";

export const SET_TRANSACTION = "SET_TRANSACTION";
export const ClEAR_TRANSACTION = "CLEAR_TRANSACTION";

export const SET_CURRENT_CATEGORY = "SET_CURRENT_CATEGORY";